version: '3'
services:
  web:
    build:
      context: .
      dockerfile: DockerFileDev
    ports:
      - "8080:8080"
      - "8081:8081"
    command: polymer serve -H 0.0.0.0
    volumes: 
      - .:/code
      - /code/bower_components